version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - 8000-8999:8000-8999
      - 443:443
    environment:
      - NVM_DIR=/home/devuser/.nvm
    command: /bin/zsh -c "while sleep 1000; do :; done"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
