version: '3'
services:
  app:
    image: "docker.io/graezykev/dev-container-base-image:latest"
    volumes:
      - ..:/workspace:cached
    ports:
      - 8000-8999:8000-8999
      - 443:443
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - NVM_DIR=$HOME/.nvm
    command: /bin/zsh -c "while sleep 1000; do :; done"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

# For Data Persistence
volumes:
  postgres-data: