version: '3'
services:
  shared-service:
    image: "docker.io/graezykev/dev-container-base-image:latest"
    volumes:
      - ..:/workspace:cached  # Mount the parent directory into the container's /workspace directory
    ports:
      - 8000-8999:8000-8999
      - 443:443
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - NVM_DIR=$HOME/.nvm  # Set NVM_DIR to the .nvm directory in the home directory
    depends_on:
      - postgres
    command: /bin/zsh -c "while sleep 1000; do :; done"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Named volume for persisting PostgreSQL data
    ports:
      - 5432:5432

volumes:
  postgres-data:  # Define a named volume for PostgreSQL data persistence
